module Ec1 module Supervision module Clusters

# system
EC1_MACHINE_HOSTNAME = ""
EC1_MACHINE_SSH_PORT = ""
EC1_ENTITY_DOMAIN = ""
# root
EC1_ROOT_NAME = ""
EC1_ROOT_EMAIL = ""
EC1_ROOT_PASSWORD = ""
# mainuser
EC1_MAINUSER_NAME = ""
EC1_MAINUSER_UID = ""
EC1_MAINUSER_GID = ""
EC1_MAINUSER_EMAIL = ""
EC1_MAINUSER_PASSWORD = ""
EC1_MAINUSER_AUTHORIZED_KEYS = ""

# extra
EC1_MACHINE_TEMP_IP = ""
EC1_MACHINE_TEMP_SSH_PORT = ""
EC1_ROOT_SSH_DEFCERT_PASSCODE = ""
EC1_MAINUSER_SSH_DEFCERT_PASSCODE = ""

end end end
