module Ec1 module Supervision module Clusters

EC1_MACHINE_SSH_PORT = ""
EC1_ENTITY_DOMAIN = ""
EC1_MACHINE_HOSTNAME = ""
EC1_MAINUSER_PASSWORD = ""
EC1_MAINUSER_UID = ""
EC1_USER_NAME = ""
EC1_MAINUSER_GID = ""
EC1_MAINUSER_EMAIL = ""
EC1_MAINUSER_AUTHORIZED_KEYS = ""
EC1_ROOT_PASSWORD = ""
EC1_ROOT_NAME = ""

end end end

