#!/usr/bin/env bash
# https://raw.github.com/epiculture/ec1_supervision_templates/master/ub10.04_x86_64/mu/system_variation_01/00ini/ec1_install_system

umask 027
ufw allow 22/tcp
ufw --force enable

ec1_user_inidir='/.ec1.ini'

ec1_system_basedir='/.ec1'

if [[ ! -d $ec1_system_basedir ]]
then
    mkdir $ec1_system_basedir
    chmod g+s $ec1_system_basedir
    echo "created dir $ec1_system_basedir"
else
    echo "ERROR: directory $ec1_system_basedir exists already"
    exit 1
fi

cd $ec1_system_basedir

repositories=(
	ec1_system_livelinks
	ec1_supervision_templates
	)

for repository in ${repositories[@]}
do
    echo "cloning https://github.com/epiculture/${repository}.git"
    git clone git://github.com/epiculture/${repository}.git
done

rsync -avh --no-o --no-g --stats $ec1_system_basedir/ec1_supervision_templates/mu/ub10.04_x86_64/system_variation_01/ $ec1_system_basedir/00mu/

rm -R $ec1_system_basedir/ec1_supervision_templates

cp /etc/network/interfaces /.ec1/00mu/network/00livelinks/interfaces/interfaces_00ori
mv /etc/network/interfaces /.ec1/00mu/network/00livelinks/interfaces/
ln -s /.ec1/00mu/network/00livelinks/interfaces/interfaces /etc/network/

mv /etc/pam.d/common-session /.ec1/00mu/pam/00livelinks/etc_common-session/common-session_00ori
ln -s /.ec1/00mu/pam/00livelinks/etc_common-session/common-session /etc/pam.d/

mv /etc/apt/sources.list /.ec1/00mu/apt/00livelinks/sources.list/sources.list_00ori
ln -s /.ec1/00mu/apt/00livelinks/sources.list/sources.list /etc/apt/

mv /etc/fstab /.ec1/00mu/mount/00livelinks/fstab/
ln -s /.ec1/00mu/mount/00livelinks/fstab/fstab /etc/

ln -s /.ec1/00mu/rvm/00livelinks/etc_rvmrc/rvmrc /etc/

DEBIAN_FRONTEND=noninteractive aptitude update; aptitude full-upgrade -y

aptitude install debconf-utils -y
echo "dash dash/sh boolean false"| debconf-set-selections; dpkg-reconfigure -f noninteractive dash
echo 'postfix postfix/main_mailer_type        select  Internet Site' | debconf-set-selections
echo 'postfix postfix/mailname        string  dummy.3eclipses.com' | debconf-set-selections
aptitude install ntp sshfs shorewall mc tar gzip lzma rar unrar bzip2 arj lha rpm unace zip unzip p7zip vim clamav ncdu htop ttf-ubuntu-font-family ttf-droid ttf-liberation screen postfix mailutils -y
aptitude clean

groupadd ec1_local
chgrp -R ec1_local $ec1_system_basedir
mkdir /00transfert
chgrp ec1_local /00transfert
chmod 770 /00transfert

touch $ec1_user_inidir/.system_ini.done

reboot

# ____________________________________________________________________
# ᨊ ᨉ  LICENSE ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ ᨊ ᨉ
# This file is part of the libre project Epiculture, distributed under
# the GNU GPLv3 license ( www.epiculture.org/ec1_core/LICENSE )
# Copyright 2005-2012 Pierre-Maël Crétinon
# ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# vim: ft=sh
