#!/usr/bin/env bash

umask 007

ec1_user_basedir="$HOME/.ec1"
ec1_user_mu_basedir="$HOME/.ec1/00mu"

check_directories=(
		$ec1_user_basedir
		$HOME/.ssh
		)

for check_directory in ${check_directories[@]}
do
    if [[ -d $check_directory ]]
    then
	echo "ERROR: directory $check_directory exists already"
	exit 1
    fi
done

mkdir -p $ec1_user_mu_basedir
echo "created dir $ec1_user_mu_basedir"
cd $ec1_user_basedir

repositories=(
	ec1_lib
	ec1_core
	ec1_core_livelinks
	ec1_xtra
	ec1_xtra_livelinks
	ec1_supervision_templates
	)

for repository in ${repositories[@]}
do
    echo "cloning git://github.com/epiculture/${repository}.git"
    git clone git://github.com/epiculture/${repository}.git
done

rsync -avh --no-o --no-g --stats $ec1_user_basedir/ec1_supervision_templates/mu/ub11.04_x86_64/root_variation_01/ $ec1_user_mu_basedir/

rm -R $ec1_user_basedir/ec1_supervision_templates

mkdir $HOME/.ssh
chmod 700 $HOME/.ssh
echo "created dir $HOME/.ssh"

ln -s $HOME/.ec1/00mu/openssh/00livelinks/config/config $HOME/.ssh/
ln -s $HOME/.ec1/00mu/openssh/00livelinks/authorized_keys/authorized_keys $HOME/.ssh/
ln -s $HOME/.ec1/00mu/openssh/00certificates/id_rsa $HOME/.ssh/
ln -s $HOME/.ec1/00mu/openssh/00certificates/id_rsa.pub $HOME/.ssh/

mv $HOME/.profile $HOME/.ec1/00mu/bash/00livelinks/.profile/.profile_00ori
ln -s $HOME/.ec1/00mu/bash/00livelinks/.profile/.profile $HOME/

mv $HOME/.bashrc $HOME/.ec1/00mu/bash/00livelinks/.bashrc/.bashrc_00ori
ln -s $HOME/.ec1/00mu/bash/00livelinks/.bashrc/.bashrc $HOME/

mkdir $HOME/.mc
ln -s $HOME/.ec1/00mu/mc/00livelinks/ini/ini $HOME/.mc/
ln -s $HOME/.ec1/00mu/mc/00livelinks/bindings/bindings $HOME/.mc/

ln -s $HOME/.ec1/00mu/screen/00livelinks/.screenrc/.screenrc $HOME/

ln -s ~/.ec1/00mu/rvm/00livelinks/.rvmrc/.rvmrc ~/

echo "root ec1 base installation finished: please copy ssh certificates to $HOME/.ec1/00mu/openssh/00certificates/"
#e_certificate_create /data1/.-.inifluxi/._.inif04/i1mu12007/root/ssh/00certificates inist03_i1root.0004_v1 [0003]

#exit

#bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer )
#exit

#rvm pkg install readline
#rvm pkg install zlib
#rvm install 1.8.7 --with-zlib-dir=$rvm_path/usr --with-readline-dir=$rvm_path/usr
#rvm use 1.8.7 --default
#rvm install 1.9.3 --with-zlib-dir=$rvm_path/usr --with-readline-dir=$rvm_path/usr
#rvm use 1.9.3 --default

#cp /etc/ssh/sshd_config $HOME/.ec1/00mu/openssh/00livelinks/etc_sshd_config/sshd_config_00ori
#mv /etc/ssh/sshd_config $HOME/.ec1/00mu/openssh/00livelinks/etc_sshd_config/
#ln -s $HOME/.ec1/00mu/openssh/00livelinks/etc_sshd_config/sshd_config /etc/ssh/
#/etc/init.d/ssh restart

#ln -s $HOME/.ec1/00mu/shorewall/00livelinks/00configs/01/in1 /etc/shorewall/
#mv /etc/shorewall/shorewall.conf $HOME/.ec1/00mu/shorewall/00livelinks/shorewall.conf/shorewall.conf_00ori
#ln -s $HOME/.ec1/00mu/shorewall/00livelinks/shorewall.conf/shorewall.conf /etc/shorewall/
#ufw disable
#shorewall start
#mv /etc/default/shorewall $HOME/.ec1/00mu/shorewall/00livelinks/etc_default/shorewall_00ori
#ln -s $HOME/.ec1/00mu/shorewall/00livelinks/etc_default/shorewall /etc/default/


#deluser --remove-all-files "erase"
#groupadd e3pblank
#useradd "e3pblank" -g "e3pblank" -G "helianova,audio,video,cdrom" -s "/bin/bash" -m
#passwd e3pblank


# vim: ft=sh
